# checkxml
TARGET_NAME:=checkxml
SYSTEM_LIBS:=libbe.so libroot.so libxml.so
MY_INCLUDES:=-I$(BUILDHOME)/headers/xml
SRCS:=$(TARGET_NAME).cpp
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/$(TARGET_NAME)
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk
