TARGET_NAME:=Network

SRC_DIR:=src/addons/print_server/transports/network

SRCS :=  NetPrint.cpp

MY_CFLAGS := -DUSE_OFFS=0 

MY_INCLUDES:= -I$(BUILDHOME)/src/inc/printclient_p

SYSTEM_LIBS:=libroot.so libbe.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:= $(INSTALL_B_BEOS_ADDONS_DIRECTORY)/Print/transport

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=

include $(SDIR_TEMPLATES)/AddonTemplate.mk

