
include $(BUILDHOME)/src/addons/input_server/methods/japanese/$(MAKEFILE_LEAFNAME)
include $(BUILDHOME)/src/addons/input_server/methods/chinese/$(MAKEFILE_LEAFNAME)

## From what I gather of the original, the softkeyboard method is no longer used.
include $(BUILDHOME)/src/addons/input_server/methods/softkeyboard/$(MAKEFILE_LEAFNAME)

