TARGET_NAME:=memusage

SRC_DIR:= src/apps/$(TARGET_NAME)

SRCS := memusage.cpp

MY_INSTALL_DIR:=$(INSTALL_APPS)

MY_CFLAGS := 

MY_INCLUDES :=

SYSTEM_LIBS:= libroot.so libbe.so

RESOURCE_FORK :=  memusage.rsrc

LINK_DIRS := $(INSTALL_USER_APPSMENU) $(INSTALL_USER_APPS)

include $(SDIR_TEMPLATES)/AppTemplate.mk
