//depot/main/src/tracker/BeOSCredits.h#48 - edit change 31089 (ubinary)
#ifndef __BEOS_CREDITS__
#define __BEOS_CREDITS__

namespace BTrackerTheft {

const char *kSanitizedCreditsString = 
	"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
	"This version of BeOS brought to you by:"
	"\n\n"
	"Engineering:"
	"\n"
	"Steve Abel, Mathias Agopian,\n"
	"Allan Anderson, Howard Berkey,\n"
	"Dave Bort, Trey Boudreau,\n"
	"Dmitriy Budko, Jeff Bush,\n"
	"Kenny Carruthers, Robert Chinn,\n"
	"Pavel Císler, John Dance,\n"
	"Marc Ferguson, Fred Fish,\n"
	"Dominic Giampaolo, Dianne Hackborn,\n"
	"Arve Hjønnevåg, George Hoffman,\n"
	"Ficus Kirkpatrick, Andrew Kimpton,\n"
	"Joe Kloss, Alfred Landrum,\n"
	"Hiroshi Lockheimer, Russ McMahon,\n"
	"Cyril Meurillon, Steven Olson,\n"
	"Jason Parks, Manuel J. Petit,\n"
	"Robert Polic, Jean-Baptiste Queru,\n"
	"Pierre Raynaud-Richard,\n"
	"Hank Sackett, Steve Sakoman,\n"
	"Jason Sams, Benoît Schillings,\n"
	"Nathan Schrenk, Leo L. Schwab,\n"
	"Brian J Swetland, Victor Tsou,\n"
	"Rico Tudor, Tinic Uro,\n"
	"Mani Varadarajan, Jon Wätte,\n"
	"Doug Wright, Alan Ellis "
	"\n\n"
	"Interaction and Interface Design:\n"
	"Bruce Browne, Timothy Martin,\n"
	"Christopher Sanders"
	"\n\n"
	"QA:"
	"\n"
	"Baron Arnold, Steven Black,\n"
	"Bret Chou, Adam Haberlach,\n"
	"Cameron MacMillan, Eric Rall,\n"
	"George F. Wong, DDS"
	"\n\n"
	"QC:"
	"\n"
	"Raymond Rodgers, Jonathan Tarbox, \n"
	"Myron Walker"
	"\n\n"
	"Documentation:"
	"\n"
	"Linda Ackerman, Doug Fulton,\n"
	"Ken McDonald, Eric Shepherd"
	"\n\n"
	"DTS:"
	"\n"
	"Marco Nelissen, Mikol Ryon,\n"
	"Owen Smith, Daniel Switkin,\n"
	"Christopher Tate, Todd Thomas"
	"\n\n"
	"Interns:"
	"\n"
	"Gregory Cobena, David Chayla,\n"
	"Travis Geiselbrecht,\n"
	"Kristoffer Nørkjær Randløv Jepsen,\n"
	"Jason Luther, Rupa Patel,\n"
	"Cody Sakoman"
	"\n\n"
	"Customer Support and Manufacturing:"
	"\n"
	"Dave Brown, Paula Draper,\n"
	"Cathryn Erickson, Katherine Strahorn,\n"
	"Brenda Walker"
	"\n\n"
	"Marketing:"
	"\n"
	"Frank Boosman, Victoria Huntzinger,\n"
	"John Mulder, Mike Popovic, Jim Rippie,\n"
	"Jon Seidenfeld, Tim Self,\n"
	"Gregory Simpson, JudeAnn Smith,\n"
	"David Willenbrink, Michelle Wright"
	"\n\n"
	"Systems administration:"
	"\n"
	"Tom Maddox, Joe Tarsha"
	"\n\n"
	"Sales:"
	"\n"
	"Karen Demps, Dave Johnson,\n"
	"Michael McBride, Mary Lou Olszemski,\n"
	"Lamar Potts, Bob Smith"
	"\n\n"
	"Legal:"
	"\n"
	"Dan Johnston"
	"\n\n"
	"Finance:"
	"\n"
	"Peter Le, Anna Lee, Al Lombardo,\n"
	"Ian Myles, Guillaume Perrotin,\n"
	"Wes Saia, Meghan Trimble"
	"\n\n"
	"CEO:"
	"\n"
	"Jean-Louis Gassée"
	"\n\n"
	"Recruiting:"
	"\n"
	"Laurie Gamelsky, Roberta Jiracek"
	"\n\n"
	"Administration:"
	"\n"
	"Misty Adams, Sabine Veyne"
	"\n\n"
	"Be Europe:"
	"\n"
	"Sébastien Bouchex, Jean Calmon,\n"
	"Marcus Jacob, Stéphane Landier,\n"
	"Marie-Francoise Lelong-Weinberg,\n"
	"Marie-Claude Levrat"
	"\n\n"
	"Be Japan:"
	"\n"
	"Takeaki Akahoshi"
	"\n\n"
	"Gone but not forgotten:"
	"\n"
	"Scott Paterson, Ron Theis,\n"
	"Bob Herold, Peter Potrebic,\n"
	"Alex Osadzinski, Valérie Peyre,\n"
	"Haru Komuro, Steve Horowitz,\n"
	"Christophe Droulers, Mark Gonzales,\n"
	"Joe Palmer, Hans Speijer,\n"
	"Bradley Taylor, Ming Low,\n"
	"Scott Barta, Trevor F Smith,\n"
	"Michael Morrissey, Sylvie Pelaprat,\n"
	"Melanie Walker, Roy Graham,\n"
	"Juli Bini, Dawn Schott,\n"
	"Guillaume Calmon, Lilia Simbe,\n"
	"Michael Alderete, Bernd Weber \n"
    "Rudi Sordes"
	"\n\n"
	"Special Thanks To:"
	"\n"
	"Duncan Wilcox, Maarten Hekkelman,\n"
	"Peter Barett, Jerome Coonen,\n"
	"Rohit Seth, Asit Mallick,\n"
	"Takekazu Okamoto, Carlin Wiegner,\n"
	"Michael Klingbeil, Justin Rowe,\n"
	"Bryce Matthews, Tommy Puett,\n"
	"William Bull, David Hinds,\n"
	"Guillaume Laforge, Chris Elkjer"
	"\n\n"
  	"Indeo® Video Software Copyright 1996-1998 Intel Corporation"
	"\n\n"
	"Portions of the technology are provided under license from RealNetworks, Inc. and its licensors"
	"\n\n"
	"MPEG Layer-3 audio compression technology licensed by Fraunhofer IIS and THOMSON multimedia "
	"http://www.iis.fhg.de/amm/"
	"\n\n";

const char *kCreditsString = 
	"\n\n\n\n\n\n\n\n\n"
	"This version of BeOS was hacked for you by:"
	"\n\n"
	"Engineering:"
	"\n"
	"Mathias \"MasterCard\" Agopian, "
	"Allan \"Spoo Boy\" Anderson, Howard Berkey, Dave \"Filterless\" Bort, "
	"Trey Boudreau, Dmitriy Budko, Jeff Bush, Kenny \"Blame Canada\" Car-rut-hers, "
	"Robert \"Rudeboy\" Chinn, Pavel \"Vabio\" \"Pablo's Sister\" Císler, "
	"John Dance, Alan \"Guitar-Boy\" Ellis, Bols Ewhac, "
	"Marc Ferguson, Fred ><>, Dominique Benji \"Nantucket\" Giampaolo, "
	"Dianne Hackborn, "
	"Arve Hjønnevåg, George \"Anatoly\" Hoffman, Ficus \"Teflon-Coated\" \"Tori\" Kirkpatrick, "
	"Andrew \"INS\" Kimpton, Joe Kloss, Alfred Landrum, Frank Hiroshi Hiro-Chan Lockheimer, Russ McMahon, "
	"Cyril \"Hero w/ Slippers\" Meurillon, Steven \"hoops\" Olson, "
	"Jason Parks, Robert Polic, Manuel J. \"The Duck\" Petit,"
	"Jean-Baptiste Queru, Pierre Raynaud-Richard, Hank Sackett, Steve Sakoman, Jason Sams, "
	"Benoît \"Godfather\" Schillings, Nathan Schrenk, "
	"Brian J Swetland, Victor \"Tinky Winky\" Tsou, Rico \"_\" Tudor, Todd \"didn't know I had a stunt cat\" Thomas, "
	"Tinic \"FreeStyle\" Uro, Mani Varadarajan, Jon \"h+\" \"Disco\" Wätte, dug wright"
	"\n\n"
	"Interaction and Interface Design:"
	"\n"
	"Bruce Browne, Timothy \"bigtime_t\" Martin, Christopher Sanders"
	"\n\n"
	"QA:"
	"\n"
	"Baron \"Big MP\" Arnold, Steven \"Immoral Authority\" Black, Bret \"Hit Man\" Chou, "
	"Adam Haberlach, Cameron MacMillan, Eric Rall, George \"The Bargain King\" Wong"
	"\n\n"
	"QC:"
	"\n"
	"Raymond \"Sith Lord\" Rodgers, Jonathan Tarbox, \n"
	"Myron \"The Plumber\" Walker"
	"\n\n"
	"Documentation:"
	"\n"
	"Linda Ackerman, Doug Fulton, Ken McDonald, Eric Shepherd"
	"\n\n"
	"DTS:"
	"\n"
	"Stephen \"Hippo\" Abel, Marco Nelissen, Mikol \"He's baaaack!\" Ryon, Owen Smith, "
	"Daniel \"Pulse\" Switkin, Christopher Tate"
	"\n\n"
	"Interns:"
	"\n"
	"Gregory Cobena, David Chayla, Travis Geiselbrecht, Kristoffer Nørkjær Randløv Jepsen, "
	"Jason Luther, Rupa Patel, Cody \"Cam\" Sakoman"
	"\n\n"
	"Customer Support and Manufacturing:"
	"\n"
	"Dave Brown, Paula Draper, Cathryn Erickson,  "
	"Katherine Strahorn, Brenda Walker"
	"\n\n"
	"Marketing:"
	"\n"
	"Frank \"Chippers Please\" Boosman, Dave Johnson, Victoria Huntzinger, "
	"John Mulder, Mike \"BeDope\" Popovic, Jim Rippie, Jon Seidenfeld, Tim Self, Gregory Simpson, JudeAnn Smith, "
	"David Willenbrink, Michelle Wright"
	"\n\n"
	"Systems administration:"
	"\n"
	"Tom Maddox, Joe Tarsha"
	"\n\n"
	"Sales:"
	"\n"
	"Karen Demps, Dave Johnson, Michael McBride, Mary Lou Olszemski, Lamar Potts, Bob Smith"
	"\n\n"
	"Legal:"
	"\n"
	"Dan Johnston"
	"\n\n"
	"Finance:"
	"\n"
	"Peter Le, Anna Lee, Al Lombardo, Ian Myles, Guillaume Perrotin, "
	"Wes Saia, Meghan Trimble"
	"\n\n"
	"CEO:"
	"\n"
	"Jean-Louis Gassée"
	"\n\n"
	"Recruiting:"
	"\n"
	"Laurie \"Shrewish Wench\" Gamelsky, Roberta Jiracek"
	"\n\n"
	"Administration:"
	"\n"
	"Misty Adams, Sabine Veyne"
	"\n\n"
	"Be Europe:"
	"\n"
	"Sébastien Bouchex, Jean Calmon, Marcus Jacob, Stéphane Landier, "
	"Marie-Francoise Lelong-Weinberg, Marie-Claude Levrat"
	"\n\n"
	"Be Japan:"
	"\n"
	"Takeaki Akahoshi"
	"\n\n"
	"Gone but not forgotten:\n"
	"Scott Paterson, Ron Theis, Bob Herold, Peter Potrebic, Alex \"Keba-Keba\" Osadzinski, Valérie \"Snip-Snip\" Peyre, "
	"Haru Komuro, Steve Horowitz, Christophe Droulers, " 
	"Mark Gonzales, Joe Palmer, Hans Speijer, Bradley Taylor, "
	"Ming Low, Scott \"Nature Cube\" Barta, Trevor \"Fat Lady\" Smith, Michael \"Slaw Pops\" Morrissey, "
	"Sylvie Pelaprat, Melanie \"Zebulon\" Walker, Roy Graham, "
	"Juli Bini, Dawn Schott, Guillaume Calmon, Lilia Simbe, Michael Alderete, Bernd Weber, Rudi Sordes, Old Be Logo"
	"\n\n"
	"Special Thanks To:"
	"\n"
	"Duncan Wilcox, Maarten Hekkelman, Peter Barett, Jerome Coonen, "
	"Rohit Seth, Asit Mallick, Takekazu Okamoto, "
	"Carlin Wiegner, Michael Klingbeil, Justin Rowe, "
	"Bryce Matthews, Tommy Puett, William Bull, David Hinds, Guillaume Laforge, Chris Elkjer"
	"\n"
	"and..."
	"\n"
	"Boolanger, Cafe Baloney, Mex To Go, Florentines, The Koo, Sokyo Tubway, "
	"K2, Beavis, Jan's Deli, Dr. Chau's, The Hong, Cafe Romanina, "
	"Round Table, BBC, Sue's, Applewood, Ken's, Fry's, ToGo\'s, 360, Pizza Chicago, "
	"Michal Pavlicek, Power Computing, Marshall, Taylor Guitars, Fender, Ibanez, "
	"Gibson, Ampeg, Sony, Seymour Cray, Linus Torvalds, Butthead, Cygnus, "
	"Richard Stallman, Zluty Pes, Roland, Free Software Foundation, "
	"Robert Anton Wilson, Motorola, AT&T, SAS, Metrowerks, "
	"Tori Amos, Motörhead, Apple Computer, Intel, Volkswagen, Kawasaki, "
	"Mr. Hankey the Christmas Poo, Sprint, Iggy, Korg, Public Enemy, "
	"Pop Will Eat Itself, Negativland, The KLF, Hagbard Celine, "
	"The Plastic People of the Universe, Kyuss, Rob Zombie, Gritty Kitty, "
	"The Swedish Consulate of San Francisco, The Half Moon Bay Nursery, "
	"Miracle Gro, Tommy Puett, Sid Meier, William Bull, Svetlana"
	"\n"
	"Los Compañeros del Comandante: "
	"\n"
	"Don Flamingo, Professor Borax"
	"\n\n"
	"Habanero Masters:"
	"\n"
	"Adam, Baron, Bob, Daniel, Dominic, Ficus, JLG, Matt, Mikol, Pavel, Scott, Steve, Michael"
	"\n\n"
	"Grub Masters:"
	"\n"
	"Adam, Jeff, Michael, Owen, Pavel, Scott"
	"\n\n\n"
	"The blues is number one in Menlo Park"
	"\n\n";

const char *kCorporateLicense =
	"Be, BeOS, the Be and BeOS logos are trademarks or registered trademarks of "
	"Be Incorporated in the United States and other countries.  All rights reserved.";

const char *kLogoLicense =
	"BeOS 5 copyright © 1991-2000 Be Incorporated.  All rights reserved.";

const char *kRealLicense = 
	"RealPlayer technology provided under license from RealNetworks, Inc. and its licensors.";

const char *kFraunhoferLicense =
	"MPEG Layer-3 audio compression technology licensed by Fraunhofer IIS "
	"and THOMSON multimedia, http://www.iis.fhg.de/amm/";

const char *kRSALicense =
	"Contains security software licensed from RSA Data Security Inc.";

const char *kIndeoLicense =
	"Indeo ® Video Technologies in part provided by Intel Corporation, Copyright 1996-2000 Intel Corporation.";

} // namespace BTrackerTheft

#endif
