/*
** /src/exp/src/apps/showimage/ResourceData.h
**
** Automatically generated by BResourceParser on
** Tuesday, March 06, 2001 at 17:14:02.
**
*/

enum {
	R_CURS_UpDown = 1,
	R_CURS_LeftRight = 2,
	R_CURS_DiagLRUL = 3,
	R_CURS_DiagURLL = 4,
	R_CURS_Cross = 5,
	R_CURS_Move = 6
};
