TARGET_NAME:=h261.detractor

SRC_DIR:=src/addons/media/detractors/h261

SRCS := H261Detractor.cpp mmx.yuv2rgb.cpp vic28.dct.cpp vic28.generated.mkbv.cpp vic28.generated.mkhuff.cpp vic28.p64.cpp

MY_CFLAGS :=

MY_INCLUDES:= \
	-I$(BUILDHOME)/src/inc/media_p

SYSTEM_LIBS:= libroot.so libbe.so libmedia.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/media/detractors

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk
