
#makefile for epson n printer driver add-on add-ons

TARGET_NAME :=stylus_photo_2000

SRC_DIR := src/addons/print_server/new_epson/add_ons/stylus_photo_2000P

include $(call FULL_SRC_DIR, src/addons/print_server/new_epson/add_ons)/$(MAKEFILE_LEAFNAME).addon

