# Deskbar makefile
TARGET_NAME:= parrot
SRC_DIR := src/commands/$(TARGET_NAME)

RESOURCE_FORK:=

MY_INSTALL_DIR:=$(INSTALL_BIN)

SRCS := $(TARGET_NAME).cpp

MY_CFLAGS:= 

MY_INCLUDES	:= 

SYSTEM_LIBS:=  libroot.so

LINK_DIRS:=


include $(SDIR_TEMPLATES)/AppTemplate.mk

