TARGET_NAME:=mp3.writer

SRC_DIR:=src/addons/media/writers/mp3

SRCS := mp3.cpp

MY_CFLAGS :=

MY_CFLAGS += 

MY_INCLUDES:= \
	-I$(BUILDHOME)/src/inc/media_p

SYSTEM_LIBS:= libroot.so libbe.so libmedia.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/media/writers

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=

include $(SDIR_TEMPLATES)/AddonTemplate.mk

