
# beinstall
TARGET_NAME:=beinstall
SYSTEM_LIBS:= libroot.so
MY_INCLUDES:=
SRCS:=main.c copyattr.c create_dir.c
SRC_DIR:=src/commands/beinstall
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/HostAppTemplate.mk

# beinstall
TARGET_NAME:=beinstall
SYSTEM_LIBS:= libroot.so
MY_INCLUDES:=
SRCS:=main.c copyattr.c create_dir.c
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/beinstall
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk
