# listres
TARGET_NAME:=listres
SYSTEM_LIBS:=libbe.so libroot.so
MY_INCLUDES:=
SRCS:=$(TARGET_NAME).cpp
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/$(TARGET_NAME)
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk
