
#makefile for epson n printer driver add-on add-ons

TARGET_NAME := stylus_pro_XL

SRC_DIR := src/addons/print_server/new_epson/add_ons/stylus_pro_xl

MY_VERSION := -app 6 0 0 -short "Epson printer add-on" -long "Epson printer add-on"

include $(call FULL_SRC_DIR, src/addons/print_server/new_epson/add_ons)/$(MAKEFILE_LEAFNAME).addon


