
include $(call INCLUDE_IF_AVAILABLE, \
	bt848 \
	dc10 \
	decoder_node \
	decoders \
	detractors \
	dv \
	emu10k \
	encoders \
	extractor \
	extractors \
	game \
	jpeglib \
	lego \
	mixer \
	multi \
	videowindow \
	writers \
, src/addons/media)

