
TARGET_NAME:=webpad.accelerant

SRC_DIR:=src/addons/accelerants/webpad

SRCS		:= accelerant.c

MY_CFLAGS := -D_BUILDING_accelerant=1

MY_INCLUDES:= -I $(BUILDHOME)/$(SRC_DIR)/inc210 -I$(BUILDHOME)/src/inc/graphics_p 

SYSTEM_LIBS:=libroot.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/accelerants

LINK_DIRS:=

SIGNATURE:= "application/x-vnd.Be-webpad.accelerant"

RESOURCES:=

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk
