
TARGET_NAME:=net_node

SRC_DIR:=src/addons/binder/net_node

SRCS := NetNode.cpp

MY_CFLAGS := 

MY_INCLUDES:= \
	-I$(BUILDHOME)/src/inc/os_p \
#	-I.

SYSTEM_LIBS:= libroot.so libbe.so libsocket.so libnetconfig.so 

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/binder

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk

