/*
** /boot/develop/be/exp/exp/duncan/qres/quickres/resparser/test/Types.h
**
** Automatically generated by BResourceParser on
** Thursday, March 23, 2000 at 15:58:36.
**
*/

enum {
	R_BeOSBitmap = 1,
	R_Boolean = 1,
	R_Point = 1,
	R_Int8 = 1,
	R_Character = 1,
	R_String = 1,
	R_Cursor = 1,
	R_Double = 1,
	R_Float = 1,
	R_Icon = 1,
	R_Int64 = 1,
	R_Int32 = 1,
	R_MIMEString = 1,
	R_Offset = 1,
	R_PNGBitmap = 2,
	R_Pointer = 1,
	R_Raw = 1,
	R_Rect = 1,
	R_Color = 1,
	R_Int16 = 1,
	R_Size = 1,
	R_Status = 1,
	R_Time = 1,
	R_UInt8 = 1,
	R_UInt64 = 1,
	R_UInt32 = 1,
	R_UInt16 = 1
};
