enProc Ellipse: "{ dup 5 mul 8 div mul exch dup mul exch add sqrt 1 exch sub }"

*DefaultTransfer: Null
*Transfer Null: "{ }"
*Transfer Null.Inverse: "{ 1 exch sub }"

*OpenUI *Smoothing:  PickOne
*OrderDependency: 50 AnySetup *Smoothing
*DefaultSmoothing: None
*Smoothing Dark: "
  2 dict
    dup /PostRenderingEnhance true put
    dup /PostRenderingEnhanceDetails
      2 dict
        dup /REValue 3 put
        dup /Type 10 put
  put setpagedevice 
"
*End
*Smoothing Medium: "
  2 dict
    dup /PostRenderingEnhance true put
    dup /PostRenderingEnhanceDetails
      2 dict
        dup /REValue 2 put
        dup /Type 10 put
  put setpagedevice 
"
*End
*Smoothing Light: "
  2 dict
    dup /PostR