
TARGET_NAME:=keyboard_watcher_node

SRC_DIR:=src/addons/binder/$(TARGET_NAME)

SRCS := KeyboardWatcherNode.cpp

MY_CFLAGS :=

MY_INCLUDES:=

SYSTEM_LIBS:= libroot.so libbe.so libexperimental.a

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/binder

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk
