
include $(call INCLUDE_IF_AVAILABLE, \
	cirrus \
	neomagic \
	supervga \
	virge \
, $(BUILDHOME)/src/addons/app_server)

# include $(BUILDHOME)/src/addons/app_server/s3/GNUmakefile
# include $(BUILDHOME)/src/addons/app_server/stub/GNUmakefile
# include $(BUILDHOME)/src/addons/app_server/vesa/GNUmakefile

