
TARGET_NAME:=mergeres

SRC_DIR:=src/commands/restools/$(TARGET_NAME)

SRCS :=  \
	$(TARGET_NAME).cpp

SYSTEM_LIBS:= libroot.so libbe.so

RESOURCES:= $(TARGET_NAME).r


MY_INSTALL_DIR:=$(INSTALL_BIN)

include $(SDIR_TEMPLATES)/AppTemplate.mk

