
FILES := Profiler
SRC_DIR:=src/apps/beide/devtools/profiling/Profilerapp
MY_INSTALL_DIR := $(INSTALL_PROFILING)
PERMISSIONS := $(PERMS_SYSTEM_APP)
include $(SDIR_TEMPLATES)/DataTemplate.mk

FILES := libprof.a libprof.h
SRC_DIR:=src/apps/beide/devtools/profiling/profilinglib
MY_INSTALL_DIR := $(INSTALL_PROFILING)
PERMISSIONS := $(PERMS_SYSTEM_DATA)
include $(SDIR_TEMPLATES)/DataTemplate.mk
