
TARGET_NAME:=intraff
SYSTEM_LIBS:= libroot.so
SRCS:=$(TARGET_NAME).c
MY_INCLUDES += -I$(BUILDHOME)/src/inc/os_p
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/$(TARGET_NAME)
include $(SDIR_TEMPLATES)/AppTemplate.mk
