
TARGET_NAME:= nuconversion
TEST_PATH:=src/kit/nutextencoding/tests
SRC_DIR:=$(TEST_PATH)/nuconversion
SRCS := nuconversion.cpp

MY_CFLAGS:=
MY_INCLUDES:= 
SYSTEM_LIBS:= libroot.so libnutextencoding.so 

RESOURCE_FORK:=

MY_INSTALL_DIR := $(BUILDHOME)/$(TEST_PATH)/regress
MY_OPTIMIZER:=-O3
PROFILE_ME:= true
include $(SDIR_TEMPLATES)/AppTemplate.mk


