
include $(call INCLUDE_IF_AVAILABLE, \
	addons \
	apps \
	bone \
	boot \
	commands \
	demos \
	drivers \
	fs \
	kit \
	modules \
	nubar \
	nukernel \
	preferences \
	resources \
	servers \
	settings \
	tools \
	tracker \
	zrecover/tools \
, src)

