
include $(call INCLUDE_IF_AVAILABLE, \
	background \
	calibrate \
	colors \
	devices \
	drive \
	email \
	fontPanel \
	japanese \
	joysticks \
	keyboard \
	keymap \
	media \
	menus \
	mime \
	mouse \
	screen \
	screensaver \
	scrollbar \
	printers \
	sounds \
	time \
	translations \
	vm \
	workspace \
, src/preferences)

# Not Ready: \
	desktop \
	cifssetup \
#
# Not In Exp: \
#
# Obsolete: \
	dialupnetworking \
	isaconfig \
	mediaservices \
	network \
	video \
