
include $(call INCLUDE_IF_AVAILABLE, \
	stylus_600 \
	stylus_670 \
	stylus_740 \
	stylus_760 \
	stylus_777 \
	stylus_800 \
	stylus_850 \
	stylus_880 \
	stylus_900 \
	stylus_980 \
	stylus_1160 \
	stylus_photo \
	stylus_photo_700 \
	stylus_photo_750 \
	stylus_photo_790 \
	stylus_photo_870 \
	stylus_photo_1270 \
	stylus_photo_ex \
	stylus_photo_2000P \
	stylus_pro \
	stylus_pro_xl \
, src/addons/print_server/new_epson/add_ons)

