TARGET_NAME:=File

SRC_DIR:=src/addons/print_server/transports/fileprint

SRCS :=  FilePrint.cpp

MY_CFLAGS := -DUSE_OFFS=0 

MY_INCLUDES:= 

SYSTEM_LIBS:=libroot.so libbe.so libtracker.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:= $(INSTALL_B_BEOS_ADDONS_DIRECTORY)/Print/transport

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk
