include $(BUILDHOME)/src/addons/email/contact_local/$(MAKEFILE_LEAFNAME)
include $(BUILDHOME)/src/addons/email/imap/$(MAKEFILE_LEAFNAME)
include $(BUILDHOME)/src/addons/email/local/$(MAKEFILE_LEAFNAME)
include $(BUILDHOME)/src/addons/email/smtp/$(MAKEFILE_LEAFNAME)
