# waitfor
TARGET_NAME:=ali
SYSTEM_LIBS:= libroot.so
MY_INCLUDES:=
SRCS		:= ali.c regcomp.c regfind.c
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/$(TARGET_NAME)
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk

