
TARGET_NAME:= basic_test

SRC_DIR:=src/kit/nutextencoding/tests/basictest
SRCS := BasicTest.cpp

MY_CFLAGS:=
MY_INCLUDES:= -I$(BUILDHOME)/src/kit/nutextencoding

SYSTEM_LIBS:= libroot.so libnutextencoding.so libtextencoding.so libbe.so

RESOURCE_FORK:=

MY_INSTALL_DIR := /source/iad/src/kit/nutextencoding/tests/basictest/

include $(SDIR_TEMPLATES)/AppTemplate.mk


