# makefile
TARGET_NAME:= strace
SRC_DIR := src/commands/be/$(TARGET_NAME)

RESOURCE_FORK:=

MY_INSTALL_DIR:=$(INSTALL_BIN)

SRCS := $(TARGET_NAME).c

MY_CFLAGS:= 

MY_INCLUDES	:= 

SYSTEM_LIBS:= libroot.so

LINK_DIRS:=


include $(SDIR_TEMPLATES)/AppTemplate.mk

