/*
  Automatically generated by 'make config' -- don't edit!
*/
#ifndef _PCMCIA_CONFIG_H
#define _PCMCIA_CONFIG_H

#define CONFIG_ISA 1
#define CONFIG_PCI 1
#define CONFIG_CARDBUS 1
#undef PCMCIA_DEBUG
//#define PCMCIA_DEBUG 10

#endif /* _PCMCIA_CONFIG_H */
