# edline makefile

TARGET_NAME:= edline

SRC_DIR := src/commands/be/edline

RESOURCE_FORK:=

MY_INSTALL_DIR:=$(INSTALL_BIN)

SRCS :=  edline.c

MY_CFLAGS:=

MY_INCLUDES	:= \

SYSTEM_LIBS:= libbe.so libroot.so

LINK_DIRS:=


include $(SDIR_TEMPLATES)/AppTemplate.mk

