TARGET_NAME:=dv.extractor

SRC_DIR:=src/addons/media/extractors/dv

SRCS := DVSplitter.cpp

MY_DFLAGS := 

MY_INCLUDES:= \
	-I$(BUILDHOME)/src/inc/media_p 

SYSTEM_LIBS:= libroot.so libbe.so libmedia.so

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/media/extractors

include $(SDIR_TEMPLATES)/AddonTemplate.mk
