# df
TARGET_NAME:=gfx_harness
SYSTEM_LIBS:=libroot.so
MY_INCLUDES:=-I$(BUILDHOME)/src/inc/graphics_p
SRCS:=harness.c
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/$(TARGET_NAME)
MY_CFLAGS:=
MY_OPTIMIZER:=-O1
include $(SDIR_TEMPLATES)/AppTemplate.mk
