# Makefile using AddonTemplate.mk
# Copyright (c) 2000-2001; Be, Inc. All Rights Reserved.

TARGET_NAME:=DumpMessage-D

SRC_DIR:=src/apps/bdb/AddOnSources

SRCS:=$(TARGET_NAME).cpp

MY_INCLUDES := -I. 

SYSTEM_LIBS:= libroot.so libbe.so

MY_INSTALL_DIR := $(INSTALL_DEVELOP)/bdb/AddOns

include $(SDIR_TEMPLATES)/AddonTemplate.mk


TARGET_NAME:=ShowBitmap-B

SRC_DIR:=src/apps/bdb/AddOnSources

SRCS:=$(TARGET_NAME).cpp

MY_INCLUDES := -I. 

SYSTEM_LIBS:= libroot.so libbe.so

MY_INSTALL_DIR := $(INSTALL_DEVELOP)/bdb/AddOns

include $(SDIR_TEMPLATES)/AddonTemplate.mk

