TARGET_NAME:=mpeg1.extractor

SRC_DIR:=src/addons/media2/extractors/mpeg1

SRCS	:= MPEGSystemExtractor.cpp 

MY_CFLAGS :=

MY_INCLUDES:= \
	-I$(BUILDHOME)/src/inc/media2_p 

SYSTEM_LIBS:= libroot.so libbe2.so libmedia2.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/media2/extractors

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk
