
include $(call INCLUDE_IF_AVAILABLE, \
	bios_node \
	user_node \
	recovery_node \
	auto_mounter_node \
	datetime_node \
	status_node \
	sony_status_node \
	extension_map_node \
	keyboard_watcher_node \
	notification_node \
	mailcache_node \
	net_node \
	net_endpoint_node \
, $(BUILDHOME)/src/addons/binder)

