
TARGET_NAME:=switchboard

SRC_DIR:=src/addons/smoove/instant_messaging

SRCS := Switchboard.cpp

MY_CFLAGS := -DUSE_OFFS=0

MY_INCLUDES:= -I$(BUILDHOME)/headers/im

SYSTEM_LIBS:= libroot.so libbe.so libim.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/smoove

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk
