TARGET_NAME:= diffa
SRC_DIR:=src/commands/be/diffa
SRCS := main.cpp AttributeList.cpp
MY_CFLAGS:= 
MY_INCLUDES:= 
SYSTEM_LIBS:= libroot.so libstdc++.r4.so
include $(SDIR_TEMPLATES)/HostAppTemplate.mk
