# copyindex
TARGET_NAME:=copyindex
SYSTEM_LIBS:= libroot.so
MY_INCLUDES:=
SRCS:=$(TARGET_NAME).c
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/be/index
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk

# lsindex
TARGET_NAME:=lsindex
SYSTEM_LIBS:= libroot.so
MY_INCLUDES:=
SRCS:=$(TARGET_NAME).c
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/be/index
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk

# mkindex
TARGET_NAME:=mkindex
SYSTEM_LIBS:= libroot.so
MY_INCLUDES:=
SRCS:=$(TARGET_NAME).c
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/be/index
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk

# rmindex
TARGET_NAME:=rmindex
SYSTEM_LIBS:= libroot.so
MY_INCLUDES:=
SRCS:=$(TARGET_NAME).c
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/be/index
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk