TARGET_NAME:=	dvi-adpcm.media2_addon

SRC_DIR:= src/addons/media2/decoders/dvi-adpcm

SRCS := \
			adpcm.c						\
			DVIADPCMDecoder.cpp 		\
			DVIADPCMDecoderAddon.cpp	\
#

MY_DFLAGS :=

MY_DFLAGS +=

MY_INCLUDES:=
#

SYSTEM_LIBS:= libroot.so libbe2.so libmedia2.so
#

HAS_MAIN:= false

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/media2/decoders

include $(SDIR_TEMPLATES)/AddonTemplate.mk
