
TARGET_NAME:= validate

SRC_DIR:=src/kit/nutextencoding/tests/validate
SRCS := validate.cpp

MY_CFLAGS:=
MY_INCLUDES:= 

SYSTEM_LIBS:= libroot.so libnutextencoding.so

RESOURCE_FORK:=

MY_INSTALL_DIR := /source/iad/src/kit/nutextencoding/tests/validate/
MY_OPTIMIZER:=-O1
include $(SDIR_TEMPLATES)/AppTemplate.mk


