
include $(call INCLUDE_IF_AVAILABLE, \
	3c503 \
	appletalk \
	dp83815 \
	ec9xx \
	eepro100 \
	homelan \
	netmate \
	ne2000 \
	ne2000pci \
	ne2000pcmcia \
	ppp \
	rangelan \
	rtl8139 \
	tulip \
	wavelan \
, $(BUILDHOME)/src/addons/net_server)

# XXX - Please add when we need PPC support
# include $(BUILDHOME)/src/addons/net_server/gce/GNUmakefile

