# addattr
TARGET_NAME:=addattr
SYSTEM_LIBS:= libroot.so libbe.so
MY_INCLUDES:=
SRCS:=$(TARGET_NAME).cpp
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/$(TARGET_NAME)
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk
