TARGET_NAME:=MakeArchive

SRC_DIR:=src/addons/tracker/makearchive

SRCS :=  MakeArchive.cpp

MY_CFLAGS :=  -DUSE_OFFS=0

MY_INCLUDES:= 

SYSTEM_LIBS:=libroot.so libbe.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/Tracker

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=$(TARGET_NAME).rsrc

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk
