const char *legalDisclaimer = 
"BE INCORPORATED – END USER LICENSE AGREEMENT\n"
"\n"
"NOTICE:  READ THIS BEFORE INSTALLING OR USING BeOS.\n"
"\n"
"BY INSTALLING AND/OR USING THIS VERSION OF BeOS YOU AGREE THAT YOU\n"
"HAVE READ THIS LICENSE, THAT YOU ACCEPT AND ARE BOUND BY ITS TERMS AND\n"
"CONDITIONS, AND THAT IT IS THE ONLY AGREEMENT BETWEEN BE INCORPORATED\n"
"AND YOU REGARDING THIS VERSION OF BeOS, THE INCLUDED DOCUMENTATION,\n"
"AND ANY THIRD PARTY APPLICATIONS INCLUDED HEREIN THAT DOES NOT COME\n"
"WITH ITS OWN SEPARATE LICENSE AGREEMENT (TOGETHER, THE “PROGRAM”).\n"
"IF YOU DO NOT ACCEPT THESE TERMS, YOU MUST RETURN THE PROGRAM AND ALL\n"
"PACKAGING (PACKET AND ALL OTHER MATERIALS) TO THE MERCHANT PROVIDING\n"
"YOU THE PROGRAM, WITHIN 5 DAYS OF OBTAINING THE PROGRAM, WITH YOUR\n"
"RECEIPT, AND YOUR MONEY WILL BE RETURNED.  PLEASE NOTE THAT YOU MAY\n"
"NOT USE, COPY, MODIFY OR TRANSFER THE PROGRAM OR DOCUMENTATION OR\n"
"ANY COPY, EXCEPT AS EXPRESSLY PROVIDED IN THIS AGREEMENT.\n"
"\n"
"LICENSE.\n"
"\n"
"This Program is licensed, not sold, to you.  You have a non-exclusive\n"
"and nontransferable right to use the enclosed Program.  This Program\n"
"can only be used on a single computer located in the United States and\n"
"its territories or any other country to which this Program is legally\n"
"exported.  You may physically transfer the Program from one computer\n"
"to another provided that the Program is used on only one computer at\n"
"a time. This software is considered to be in use on a computer when it\n"
"is loaded into the temporary memory (i.e. RAM)  or installed into the\n"
"permanent memory (e.g. hard drive) of that computer, except that a copy\n"
"installed on a network server for the sole purpose of distribution to\n"
"other computers is not \"in use.\"  You may merge it into another program\n"
"for your use on a single machine.  You agree that the Program belongs to\n"
"Be Incorporated and its licensors.  You agree to use your best efforts\n"
"to prevent and protect the contents of the Program from unauthorized\n"
"disclosure or use.  Be Incorporated and its licensors reserve all rights\n"
"not expressly granted to you.\n"
"\n"
"LIMITATIONS ON USE.  You may not rent, lease, sell or otherwise\n"
"transfer or distribute copies of the Program to others.  You may not\n"
"modify or translate the Program without the prior written consent of\n"
"Be Incorporated.  You may not reverse assemble, reverse compile or\n"
"otherwise attempt to create the source code from the Program. You shall\n"
"not use Be Incorporated's name or refer to Be Incorporated directly or\n"
"indirectly in any papers, articles, advertisements, sales presentations,\n"
"news releases or releases to any third party without the prior written\n"
"approval of Be Incorporated for each such use.  You shall not release\n"
"the results of any performance or functional evaluation of any portion\n"
"of the Program to any third party without prior written approval of Be\n"
"Incorporated for each such release.\n"
"\n"
"BACKUP AND TRANSFER.  You may make one copy of the Program for\n"
"backup purposes if Be Incorporated's copyright notice is included. You may\n"
"not sublicense the Program, or assign, delegate or otherwise transfer\n"
"this license or any of the related rights or obligations for any reason.\n"
"Any attempt to make any such sublicense, assignment, delegation or other\n"
"transfer by you shall be void.\n"
"\n"
"COPYRIGHT.  The Program is copyrighted. You may not copy the Program\n"
"except to provide a backup copy and to load the Program into the computer\n"
"as part of executing the Program.  Any and all other copies of the\n"
"Program made by you are in violation of this license.\n"
"\n"
"OWNERSHIP.  You agree that you neither own nor hereby acquire any claim or\n"
"right of ownership to the Program or to any related patents, copyrights,\n"
"trademarks or other intellectual property.  You own only the magnetic\n"
"or other physical media on which the Program is recorded or fixed.\n"
"Be Incorporated and its licensors retain all right, title and interest\n"
"in and to all copies of  the Program as recorded on the original media\n"
"and all subsequent copies of the Program at all times, regardless of the\n"
"form or media in or on which the original or other copies may subsequently\n"
"exist.  This license is not a sale of the original or any subsequent copy.\n"
"\n"
"TERM AND TERMINATION.  This license is effective until terminated.\n"
"You may terminate this license at any time by destroying the Program\n"
"and all permitted backup copies.  This license automatically terminates\n"
"if you fail to comply with its terms and conditions.  You agree that,\n"
"upon such termination, you will destroy (or permanently erase) all\n"
"copies of the Program.  You also agree that, upon termination, you will\n"
"return the original Program to the Merchant providing you the Program,\n"
"together with any other material you have received from Be Incorporated\n"
"or its distributors in connection with the Program.\n"
"\n"
"WARRANTY DISCLAIMER.  BE INCORPORATED AND ITS LICENSORS PROVIDE THE\n"
"PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS, IMPLIED OR\n"
"STATUTORY, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF TITLE,\n"
"MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.\n"
"BE INCORPORATED AND ITS LICENSORS DO NOT AND CANNOT WARRANT THE\n"
"PERFORMANCE OR RESULTS YOU MAY OBTAIN, OR THE INTERACTION WITH OTHER\n"
"PROGRAMS AND/OR DATA YOU HAVE ON YOUR COMPUTER BY YOUR INSTALLATION\n"
"AND/OR USE OF THE PROGRAM.\n"
"\n"
"Some states do not allow the exclusion of implied warranties, so the\n"
"above exclusion may not apply to you.  This warranty gives you specific\n"
"legal rights and you may also have other rights which vary from state\n"
"to state.  The Program may have been delivered to you bundled with third\n"
"party software applications not owned by Be Incorporated.\n"
"\n"
"SUCH THIRD PARTY SOFTWARE IS PROVIDED TO YOU “AS IS” AND WITHOUT\n"
"WARRANTY OF ANY KIND BY BE INCORPORATED EITHER EXPRESS, IMPLIED OR\n"
"STATUTORY, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF TITLE,\n"
"MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.\n"
"\n"
"Your rights and warranties, if any, regarding such third party software\n"
"are governed by such third party’s own end user license agreement and\n"
"not by Be Incorporated.\n"
"\n"
"LIMITATION OF REMEDIES.  Be Incorporated and its licensors' entire\n"
"liability and your exclusive remedy in connection with the program and\n"
"the documentation shall be that you are entitled to return the defective\n"
"media containing the program together with the documentation to the\n"
"merchant.  At the option of the merchant, you may receive replacement\n"
"media containing the program and documentation that conforms with the\n"
"limited warranty or a refund of the amount paid by you.\n"
"\n"
"IN NO EVENT WILL BE INCORPORATED OR ITS LICENSORS BE LIABLE FOR ANY\n"
"INDIRECT DAMAGES OR OTHER RELIEF ARISING OUT OF YOUR USE OR INABILITY\n"
"TO USE THE PROGRAM OR ANY THIRD PARTY APPLICATIONS INCLUDING, BY WAY\n"
"OF ILLUSTRATION AND NOT LIMITATION, LOST PROFITS, LOST BUSINESS OR LOST\n"
"OPPORTUNITY, OR ANY SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING\n"
"OUT OF SUCH USE OR INABILITY TO USE THE PROGRAM OR ANY THIRD PARTY\n"
"APPLICATIONS, EVEN IF BE INCORPORATED, ITS LICENSORS OR AN AUTHORIZED\n"
"BE INCORPORATED DEALER, DISTRIBUTOR OR SUPPLIER HAS BEEN ADVISED OF THE\n"
"POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY.\n"
"\n"
"Some states do not allow the exclusion or limitation of incidental or\n"
"consequential damages so the above limitation or exclusion may not apply\n"
"to you.\n"
"\n"
"GOVERNING LAW AND GENERAL PROVISIONS.  This license will be governed by\n"
"the laws of the State of California as applied to transactions taking\n"
"place wholly within California between California residents.  This license\n"
"will not be governed by the United Nations Convention on Contracts for\n"
"the International Sale of Goods, the application of which is expressly\n"
"excluded.  If any part of this agreement is found void and unenforceable,\n"
"it will not affect the validity of the balance of the agreement, which\n"
"shall remain valid and enforceable according to its terms.  You agree\n"
"that the Program will not be shipped, transferred or exported into any\n"
"country or used in any manner prohibited by any U.S. export control laws.\n"
"\n"
"NOTICE TO U.S. GOVERNMENT END USERS.  The Program is a \"commercial\n"
"item,\" as that term is defined at 48 C.F.R. 2.101 (OCT 1995), consisting\n"
"of \"commercial computer software\" and \"commercial computer software\n"
"documentation,\" as such terms are used in 48 C.F.R. 12.212 (SEPT 1995)\n"
"and is provided to the U.S. Government only as a commercial end item.\n"
"Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through\n"
"227.7202-4 (JUNE 1995), all U.S. Government End Users acquire the program\n"
"with only those rights set forth herein.\n"
;
