# Makefile using CompileObjectsTemplate.mk

SRC_DIR		:= src/kit/binder_addon_glue

SRCS :=  \
	binder_addon_glue.cpp

MY_CFLAGS:=

MY_INCLUDES:=	\

OBJ_DIR := $(CREATED_LIBRARY_PATH)
MY_TRASH_ID := binder_addon_glue

MY_INSTALL_DIR := $(INSTALL_DEV_LIBS)

include $(SDIR_TEMPLATES)/CompileObjectsTemplate.mk

