# Makefile

include $(call INCLUDE_IF_AVAILABLE, \
	3dfx \
	ati \
	g400 \
	i740 \
	i810 \
	matrox \
	neomagic \
	nvidia \
	rage128 \
	radeon \
	SiS \
	stub \
	trident \
	lynxem \
	null \
	webpad \
,src/addons/accelerants)

