
include $(call INCLUDE_IF_AVAILABLE, \
	assert \
	csu \
	ctype \
	dirent \
	io \
	libio \
	locale \
	malloc \
	math \
	misc \
	posix \
	setjmp \
	signal \
	stdio-common \
	stdlib \
	string \
	time \
	wcsmbs-utf \
	wctype \
, src/kit/glibc)
