# Makefile
TARGET_NAME:=gameaudiomix
SRC_DIR:=src/commands/$(TARGET_NAME)

SYSTEM_LIBS:= libroot.so libbe.so libmedia.so
MY_INCLUDES:=-I$(BUILDHOME)/src/inc/driver
SRCS:=$(ALL_DOT_CPP)
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk
