TARGET_NAME:=	mixer2.media_addon

SRC_DIR:=		src/addons/media2/mixer

SRCS:=			MixerCoreNode.cpp MixerInput.cpp MixerOutput.cpp

MY_CFLAGS:=
MY_INCLUDES:= \
	-I$(BUILDHOME)/src/inc/media2_p

SYSTEM_LIBS:=	libroot.so libbe2.so libmedia2.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/media2

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=

include $(SDIR_TEMPLATES)/AddonTemplate.mk
