# strings
TARGET_NAME:=sstrings
SYSTEM_LIBS:= libroot.so
MY_INCLUDES:=
SRCS:=strings.c
RESOURCE_FORK:=
LINK_DIRS:=
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/strings
MY_CFLAGS:=

include $(SDIR_TEMPLATES)/AppTemplate.mk
