# makefile
TARGET_NAME:= mimeset
SRC_DIR := src/commands/be/$(TARGET_NAME)

RESOURCE_FORK:= $(TARGET_NAME).rsrc

MY_INSTALL_DIR:=$(INSTALL_BIN)

SRCS := main.cpp

MY_CFLAGS:= 

MY_INCLUDES	:= -I$(BUILDHOME)/src/inc/app_p

SYSTEM_LIBS:= libbe.so libroot.so

LINK_DIRS:=


include $(SDIR_TEMPLATES)/AppTemplate.mk

