TARGET_NAME:=midi.detractor

SRC_DIR:=src/addons/media/detractors/midi

SRCS	:= MidiDetractor.cpp

MY_CFLAGS :=

MY_INCLUDES:= \
	-I$(BUILDHOME)/src/inc/media_p -I$(BUILDHOME)/src/kit/bae

SYSTEM_LIBS:= libroot.so libbe.so libmedia.so libbae.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/media/detractors

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk
