TARGET_NAME:=LPR

SRC_DIR:=src/addons/print_server/transports/lpr

SRCS :=  lpr.cpp

SYSTEM_LIBS:=libroot.so libbe.so \
	libsocket.so libbnetapi.so

MY_INSTALL_DIR:= $(INSTALL_B_BEOS_ADDONS_DIRECTORY)/Print/transport

include $(SDIR_TEMPLATES)/AddonTemplate.mk
