TARGET_NAME:=dvaudio.decoder

SRC_DIR:=src/addons/media/decoders/dvaudio

SRCS := dvaudio.cpp

MY_CFLAGS :=

MY_INCLUDES:= \
	-I$(BUILDHOME)/src/inc/media_p \

SYSTEM_LIBS:= libroot.so libbe.so libmedia.so \
#

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/media/decoders

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=

include $(SDIR_TEMPLATES)/AddonTemplate.mk
