TARGET_NAME:=NetronDisplayConfig
MY_INSTALL_DIR:=$(INSTALL_APPS)

SRC_DIR:= src/apps/netrondisplayconfig
SRCS:= $(ALL_DOT_CPP)

MY_CFLAGS :=

MY_INCLUDES := -I$(BUILDHOME)/headers/experimental

SYSTEM_LIBS:= libbe.so libroot.so libpng.so libexperimental.a

//RESOURCE_FORK:= $(TARGET_NAME).rsrc
RESOURCE_FORK:= 

LINK_DIRS := $(INSTALL_USER_APPSMENU) $(INSTALL_USER_APPS)

MY_CFLAGS:=



include $(SDIR_TEMPLATES)/AppTemplate.mk
