#!/bin/sh

# 
# If a memory stick with the SonyDisplayTest tool is inserted at 
# boot time, the SonyDisplayTest should start up
# Notice that the SonyDisplayTest can also be started at boot time
# by holding down the web+email buttons.  That happens whether
# there is a memory stick inserted or not.
#

alert "Insert a MemoryStick and click 'OK' when it is shown mounted on the desktop."
# Sorry, if this disk used to have a validation suite, it doesn't anymore
rm -rf /disk/test
mkdir /disk/test
cp /boot/beos/bin/SonyDisplayTest /disk/test
if exists /disk/test/SonyDisplayTest
	alert "DisplayTest MemoryStick successfully made." "Done"
else
	alert "Problem creating DisplayTest MemoryStick.  Please fix MemoryStick and try again."
fi