# listattr
TARGET_NAME:=listattr
SYSTEM_LIBS:=libbe.so libroot.so
SRCS:=$(TARGET_NAME).cpp
MY_INSTALL_DIR:=$(INSTALL_BIN)
SRC_DIR:=src/commands/$(TARGET_NAME)
include $(SDIR_TEMPLATES)/AppTemplate.mk
