
TARGET_NAME:=datetime_node

SRC_DIR:=src/addons/binder/datetime_node

SRCS := DateTimeNode.cpp

MY_CFLAGS := 

MY_INCLUDES:= \
	-I$(BUILDHOME)/src/inc/os_p \
#	-I.

SYSTEM_LIBS:= libroot.so libbe.so

PARENT_IMAGE:=

HAS_MAIN:=

MY_INSTALL_DIR:=$(INSTALL_ADD_ONS)/binder

LINK_DIRS:=

SIGNATURE:=

RESOURCES:=

ATTRIBUTES:=


include $(SDIR_TEMPLATES)/AddonTemplate.mk

