
include $(call INCLUDE_IF_AVAILABLE, \
	BuyNow \
	DT300ScreenDimmer \
	Flip \
	Foam \
	Icons \
	Lens \
	Lissart \
	Message \
	SonyScreenDimmer \
	Spiral \
	Spots \
	StringTheme \
	SuperString \
, src/addons/screen_saver)

