#!/bin/sh

ZBEOS=zbeos
TMP_ZBEOS=/tmp/zbeos
IMAGES=/tmp/images
IMAGES_GZ=/tmp/images.gz

if [ "$1." != "." ]
then
	ZBEOS=$1
fi

if [ ! -f $ZBEOS ]
then
	echo Cannot find $ZBEOS
	exit 1
fi

packimages < configuration > $IMAGES
if [ $? != 0 ]
then
	echo Error packing images
	rm $IMAGES
	exit 1
fi

gzip -f $IMAGES

OFFSET=`findimages $ZBEOS`
if [ $? != 0 ]
then
	echo Error finding existing images in $ZBEOS
	rm $IMAGES_GZ
	exit 1
fi

dd if=$ZBEOS of=$TMP_ZBEOS bs=$OFFSET count=1
cat $IMAGES_GZ >> $TMP_ZBEOS
cp $TMP_ZBEOS $ZBEOS
rm -f $IMAGES_GZ $TMP_ZBEOS

echo Replaced images in $ZBEOS
